---
- name: install apache and copy all folder to remote server
  hosts: prod_servers
  become: yes

  vars:
    source_file: ./mywebsite/index.html
    destination_file: /var/www/html

  tasks:
  - name: install apache to prod servers
    apt: name=apache2 state=latest

  - name: copy index html
    copy: src={{ source_file }} dest={{ destination_file }} mode=0555
    notify: restart apache

  - name: start webservice and enable
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
