---
- name: install apache and copy all folder to remote server
  hosts: all
  become: yes

  vars:
    source_folder: ./mywebsite2
    destination_folder: /var/www/html

  tasks:
  - name: check and print linux version
    debug: var=ansible_os_family

  - block: #block for debian

     - name: install apache for debian
       apt: name=apache2 state=latest

     - name: start webservice and enable for debian
       service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"


  - block: #block for redhat

     - name: install apache for centos
       yum: name=httpd state=latest

     - name: start webservice and enable for redhat
       service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: copy files with loop
    copy: src={{ source_folder }}/{{ item }} dest={{ destination_folder }}
    loop:
     - "file1"
     - "file2"
     - "log.log"
     - "one_more"
     - "index.html"
    notify:
     - restart apache
     - restart httpd

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
  - name: restart httpd
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
